// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Valasztasok.Models;

#nullable disable

namespace Valasztasok.Migrations
{
    [DbContext(typeof(Valasztas_db_Context))]
    partial class Valasztas_db_ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("Valasztasok.Models.Jelolt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kerulet")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PartRovid_nev")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Szavazatszam")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PartRovid_nev");

                    b.ToTable("Jeloltek");
                });

            modelBuilder.Entity("Valasztasok.Models.Part", b =>
                {
                    b.Property<string>("Rovid_nev")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Teljes_nev")
                        .HasColumnType("INTEGER");

                    b.HasKey("Rovid_nev");

                    b.ToTable("Partok");
                });

            modelBuilder.Entity("Valasztasok.Models.Jelolt", b =>
                {
                    b.HasOne("Valasztasok.Models.Part", "Part")
                        .WithMany("Jeloltek")
                        .HasForeignKey("PartRovid_nev")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Part");
                });

            modelBuilder.Entity("Valasztasok.Models.Part", b =>
                {
                    b.Navigation("Jeloltek");
                });
#pragma warning restore 612, 618
        }
    }
}
